name: 'GAWG Validate Build'
description: 'This actiosn belogns to the GAWG workflow and is used to validate the configurations, Dockerfile, secrets, deployment, and runner.'
author: Álvaro García Pizarro
branding:
  icon: 'package'
  color: 'gray-dark'

inputs:
  technology:
    type: string
    description: 'Repository name with owner. For example, actions/checkout'

  docker:
    type: boolean
    description: 'Flag to validate the Dockerfile.'
    default: false

  deployment:
    type: string
    description: 'Deployment type. For example, kubernetes, helm, etc.'

  config-json:
    type: string
    description: 'JSON string with the configuration to validate.'

outputs:
  test:
    description: "test"
    value: ${{ steps.test.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - name: Test
      shell: bash
      run: |
        echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT