name: Gawg Deploy workflow

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        description: 'The name of the artifact to deploy'
        type: string
      docker:
        required: true
        description: 'Whether to deploy the artifact as a Docker container'
        type: boolean
      self-hosted-runner:
        required: true
        description: 'Whether to deploy the artifact using a self-hosted runner'
        type: boolean
      deployment:
        required: true
        description: 'The deployment environment'
        type: string
      config-json:
        required: true
        description: 'The JSON configuration for the deployment'
        type: string
    # secrets:
    #   token:
    #     required: true

jobs:
  none-deployment:
    if: ${{ inputs.deployment == 'none' }}
    runs-on: ubuntu-latest
    steps:
      - name: Skipping deployment
        shell: bash
        run: |
          echo "Skipping deployment. To deploy, set the deployment environment to a valid value."
          exit 0
  
  docker-hub:
    if: ${{ inputs.deployment == 'dockerhub' }}
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to Docker Hub
        shell: bash
        run: |
          echo "Deploying to Docker Hub"
          echo "The selected deployment is DOCKER-HUB."
          echo "To deploy to Docker Hub, make sure you have a Dockerfile in the artifact."

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      - name: Show artifact files
        shell: bash
        run: |
          echo "Make sure the artifact files are correct and there is a Dockerfile inside it."
          echo "Files in artifact:"
          ls -lah
      
      - name: Check Docker Username Credentials
        shell: bash
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME is not set. To set it, go to your repository settings > Secrets > New repository secret"
            echo "DOCKER_USERNAME is not set. To set it, go to your repository settings > Secrets > New repository secret" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Check Docker Password Credentials
        shell: bash
        run: |
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DOCKER_PASSWORD is not set. To set it, go to your repository settings > Secrets > New repository secret"
            echo "DOCKER_PASSWORD is not set. To set it, go to your repository settings > Secrets > New repository secret" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ inputs.artifact-name }}:latest .

      - name: Show Docker images
        run: |
          echo "Docker image built:"
          docker images

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ inputs.artifact-name }}:latest

      - name: Show Docker images
        run: |
          echo "Docker image pushed:"
          docker images