name: Release new V1

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  cleanup_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete all tags from remote
        run: |
          git tag -l | xargs -n 1 -I {} git push origin :{}
        shell: bash

      - name: Delete all releases
        run: |
          releases=$(gh release list --limit 100 | awk '{print $1}')
          for release in $releases; do
            gh release delete "$release" --yes
          done
        shell: bash

      - name: Create new tag v1
        run: |
          git tag v1
          git push origin v1
        shell: bash

      - name: Create new release
        run: |
          gh release create v1 --title "v1" --notes "Release v1"
        shell: bash